[workspace]
name = "mise"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[dependencies]
mise = { path = "." }
rust = "1.95.*"
cargo-nextest = ">=0.9.143,<0.10"

[tasks]
mise = "mise"
lint = "cargo fmt --all && cargo clippy --all-targets --all-features --fix --allow-dirty --allow-staged -- -D warnings"
test = "cargo nextest run --locked --color always && cargo test --doc --locked"

[package]
name = "mise"
version = "8.22.0"

[package.build-dependencies]
rust = "1.95.*"

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-rust"
version = "*"
