use std::collections::BTreeSet;
use std::path::PathBuf;

use clap::Subcommand;
use serde::Serialize;

use crate::gh::ChangedFiles;
use crate::repo::DeepstreamCfg;
use crate::types::{Arch, DeepstreamVersion};

const GLOBAL_VINCA: &[&str] = &[
    "vinca.yaml",
    "conda_build_config.yaml",
    "robostack.yaml",
    "packages-ignore.yaml",
    "rosdistro_snapshot.yaml",
];

const GLOBAL_BOTH: &[&str] = &["pixi.toml", "pixi.lock"];

const GLOBAL_BOTH_PREFIXES: &[&str] = &[
    ".github/workflows/",
    ".github/actions/",
    "scripts/",
];

#[derive(Subcommand, Debug)]
pub enum Matrix {
    /// Compute the build matrix for CI.
    Compute {
        #[arg(long)]
        repo_root: Option<PathBuf>,
    },
}

impl Matrix {
    pub fn run(self) -> anyhow::Result<()> {
        match self {
            Self::Compute { repo_root: _ } => anyhow::bail!("matrix compute: not implemented"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Pipeline {
    Vinca,
    PixiNative,
    /// Sentinel emitted when there is no work — trips a guard step in CI.
    ShouldNotRun,
}

/// One row of the matrix JSON output. Field names mirror the original Python
/// (kebab-case) so the consuming workflow YAML keeps working unchanged.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct MatrixEntry {
    pub pipeline: Pipeline,
    #[serde(rename = "target-platform")]
    pub target_platform: Arch,
    /// Empty string for non-DS rows (matches Python output exactly).
    #[serde(rename = "ds-version")]
    pub ds_version: String,
    #[serde(rename = "ds-image")]
    pub ds_image: String,
    pub runner: String,
    /// Empty for vinca and DS rows; one of "4cpu", "8cpu", "16cpu", "32cpu" for pixi-native rows.
    #[serde(rename = "runner-size")]
    pub runner_size: String,
    #[serde(rename = "artifact-name")]
    pub artifact_name: String,
}

#[derive(Debug, Default, PartialEq, Eq)]
struct MatrixState {
    vinca: bool,
    pixi_native: bool,
    ds_versions: BTreeSet<DeepstreamVersion>,
}

#[allow(dead_code)]
fn classify(changed: &ChangedFiles, ds: &DeepstreamCfg) -> MatrixState {
    let mut state = MatrixState::default();

    let paths: &[std::path::PathBuf] = match changed {
        ChangedFiles::All => {
            state.vinca = true;
            state.pixi_native = true;
            state.ds_versions = ds.versions.iter().copied().collect();
            return state;
        }
        ChangedFiles::Paths(p) => p,
    };

    for path in paths {
        let Some(p) = path.to_str() else { continue };

        if GLOBAL_VINCA.contains(&p) {
            state.vinca = true;
            state.ds_versions.extend(ds.versions.iter().copied());
            continue;
        }
        if GLOBAL_BOTH.contains(&p)
            || GLOBAL_BOTH_PREFIXES.iter().any(|prefix| p.starts_with(prefix))
        {
            state.vinca = true;
            state.pixi_native = true;
            state.ds_versions.extend(ds.versions.iter().copied());
            continue;
        }
        if p == ".github/deepstream-recipes.yaml" {
            state.vinca = true;
            state.ds_versions.extend(ds.versions.iter().copied());
            continue;
        }
        if p == "variants/deepstream.yaml" {
            state.ds_versions.extend(ds.versions.iter().copied());
            continue;
        }
        if p == "rosdistro_additional_recipes.yaml" {
            state.vinca = true;
            continue;
        }
        if p == "pixi_native_packages.yaml" {
            state.pixi_native = true;
            continue;
        }
        if let Some(rest) = p.strip_prefix("vendor_recipes/") {
            let name = rest.split('/').next().unwrap_or("");
            // RecipeName has no validation yet, so use the string directly.
            if ds.recipes.iter().any(|r| r.as_str() == name) {
                state.ds_versions.extend(ds.versions.iter().copied());
            } else {
                state.vinca = true;
            }
            continue;
        }
        // `recipes/` is generated by vinca; ignore. Everything else (docs, README) → no jobs.
        if p.starts_with("recipes/") {
            continue;
        }
    }

    state
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pipeline_serializes_to_kebab_case() {
        assert_eq!(serde_json::to_string(&Pipeline::Vinca).unwrap(), "\"vinca\"");
        assert_eq!(serde_json::to_string(&Pipeline::PixiNative).unwrap(), "\"pixi-native\"");
        assert_eq!(serde_json::to_string(&Pipeline::ShouldNotRun).unwrap(), "\"should-not-run\"");
    }

    #[test]
    fn matrix_entry_serializes_with_kebab_case_keys() {
        let e = MatrixEntry {
            pipeline: Pipeline::Vinca,
            target_platform: Arch::Linux64,
            ds_version: String::new(),
            ds_image: String::new(),
            runner: "runs-on=1/runner=4cpu-linux-x64".into(),
            runner_size: String::new(),
            artifact_name: "build-linux-64".into(),
        };
        let json = serde_json::to_string(&e).unwrap();
        assert!(json.contains("\"target-platform\":\"linux-64\""), "got: {json}");
        assert!(json.contains("\"ds-version\":\"\""), "got: {json}");
        assert!(json.contains("\"runner-size\":\"\""), "got: {json}");
        assert!(json.contains("\"artifact-name\":\"build-linux-64\""), "got: {json}");
    }

    use crate::types::{DeepstreamVersion, RecipeName};
    use std::str::FromStr;

    fn cfg(recipes: &[&str], versions: &[DeepstreamVersion]) -> DeepstreamCfg {
        DeepstreamCfg {
            recipes: recipes.iter()
                .map(|n| RecipeName::from_str(n).unwrap())
                .collect(),
            versions: versions.iter().copied().collect(),
        }
    }

    fn paths(ps: &[&str]) -> ChangedFiles {
        ChangedFiles::Paths(ps.iter().map(std::path::PathBuf::from).collect())
    }

    #[test]
    fn classify_all_means_everything() {
        let ds = cfg(&["foo"], &[DeepstreamVersion::V7_1, DeepstreamVersion::V8_0]);
        let s = classify(&ChangedFiles::All, &ds);
        assert!(s.vinca);
        assert!(s.pixi_native);
        assert_eq!(s.ds_versions.len(), 2);
    }

    #[test]
    fn classify_global_vinca_triggers_vinca_and_ds() {
        let ds = cfg(&["foo"], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&["vinca.yaml"]), &ds);
        assert!(s.vinca);
        assert!(!s.pixi_native);
        assert!(s.ds_versions.contains(&DeepstreamVersion::V7_1));
    }

    #[test]
    fn classify_global_both_triggers_everything() {
        let ds = cfg(&["foo"], &[DeepstreamVersion::V7_1, DeepstreamVersion::V8_0]);
        let s = classify(&paths(&["pixi.toml"]), &ds);
        assert!(s.vinca);
        assert!(s.pixi_native);
        assert_eq!(s.ds_versions.len(), 2);
    }

    #[test]
    fn classify_workflow_prefix_triggers_everything() {
        let ds = cfg(&[], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&[".github/workflows/build.yml"]), &ds);
        assert!(s.vinca);
        assert!(s.pixi_native);
        assert!(!s.ds_versions.is_empty());
    }

    #[test]
    fn classify_deepstream_recipes_file_triggers_vinca_and_ds() {
        let ds = cfg(&[], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&[".github/deepstream-recipes.yaml"]), &ds);
        assert!(s.vinca);
        assert!(!s.pixi_native);
        assert!(s.ds_versions.contains(&DeepstreamVersion::V7_1));
    }

    #[test]
    fn classify_variants_file_triggers_only_ds() {
        let ds = cfg(&[], &[DeepstreamVersion::V8_0]);
        let s = classify(&paths(&["variants/deepstream.yaml"]), &ds);
        assert!(!s.vinca);
        assert!(!s.pixi_native);
        assert!(s.ds_versions.contains(&DeepstreamVersion::V8_0));
    }

    #[test]
    fn classify_rosdistro_additional_triggers_vinca_only() {
        let ds = cfg(&[], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&["rosdistro_additional_recipes.yaml"]), &ds);
        assert!(s.vinca);
        assert!(!s.pixi_native);
        assert!(s.ds_versions.is_empty());
    }

    #[test]
    fn classify_pixi_native_manifest_triggers_pixi_only() {
        let ds = cfg(&[], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&["pixi_native_packages.yaml"]), &ds);
        assert!(!s.vinca);
        assert!(s.pixi_native);
        assert!(s.ds_versions.is_empty());
    }

    #[test]
    fn classify_vendor_recipes_ds_match_triggers_ds_only() {
        let ds = cfg(&["my-ds-recipe"], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&["vendor_recipes/my-ds-recipe/recipe.yaml"]), &ds);
        assert!(!s.vinca);
        assert!(!s.pixi_native);
        assert!(s.ds_versions.contains(&DeepstreamVersion::V7_1));
    }

    #[test]
    fn classify_vendor_recipes_non_ds_triggers_vinca() {
        let ds = cfg(&["other-recipe"], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&["vendor_recipes/regular-recipe/recipe.yaml"]), &ds);
        assert!(s.vinca);
        assert!(!s.pixi_native);
        assert!(s.ds_versions.is_empty());
    }

    #[test]
    fn classify_recipes_path_is_ignored() {
        let ds = cfg(&[], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&["recipes/some-generated/recipe.yaml"]), &ds);
        assert_eq!(s, MatrixState::default());
    }

    #[test]
    fn classify_unrelated_paths_yield_no_work() {
        let ds = cfg(&[], &[DeepstreamVersion::V7_1]);
        let s = classify(&paths(&["README.md", "docs/some-doc.md"]), &ds);
        assert_eq!(s, MatrixState::default());
    }
}
